-- Script para crear la tabla intermedia TURNO_SERVICIO en Oracle
-- Crea la secuencia y el trigger para el autoincremento

CREATE TABLE TURNO_SERVICIO (
    ID_TURNO_SERVICIO NUMBER PRIMARY KEY,
    ID_TURNO NUMBER NOT NULL,
    ID_SERVICIO NUMBER NOT NULL,
    PRECIO NUMBER,
    DURACION_MIN NUMBER,
    NOTAS VARCHAR2(500),
    CONSTRAINT FK_TURNO_SERVICIO_TURNO FOREIGN KEY (ID_TURNO) REFERENCES TURNOS(ID_TURNO),
    CONSTRAINT FK_TURNO_SERVICIO_SERVICIO FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIOS(ID_SERVICIO)
);

CREATE SEQUENCE SEQ_TURNO_SERVICIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TURNO_SERVICIO_ID
BEFORE INSERT ON TURNO_SERVICIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_TURNO_SERVICIO IS NULL THEN
        SELECT SEQ_TURNO_SERVICIO.NEXTVAL INTO :NEW.ID_TURNO_SERVICIO FROM DUAL;
    END IF;
END;
/

-- Puedes agregar campos adicionales si lo necesitas. Revisa los nombres y tipos según tu modelo actual.
